var userScriptingPage =
[
    [ "HCOM Scripting", "userScriptingPageHcomPage.html", [
      [ "HCOM", "userScriptingPage.html#autotoc_md0", null ],
      [ "EmbeddedScript (NumHop)", "userScriptingPage.html#autotoc_md1", null ],
      [ "Control Flow", "userScriptingPageHcomPage.html#controlflow", [
        [ "If statements", "userScriptingPageHcomPage.html#ifstatements", null ],
        [ "While loops", "userScriptingPageHcomPage.html#whileloops", null ],
        [ "Foreach loops", "userScriptingPageHcomPage.html#foreachloops", null ]
      ] ],
      [ "Simulation Commands", "userScriptingPageHcomPage.html#simulationcommands", [
        [ "sim", "userScriptingPageHcomPage.html#sim", null ],
        [ "chss", "userScriptingPageHcomPage.html#chss", null ],
        [ "chts", "userScriptingPageHcomPage.html#chts", null ],
        [ "ints", "userScriptingPageHcomPage.html#ints", null ]
      ] ],
      [ "Plot Commands", "userScriptingPageHcomPage.html#plotcommands", [
        [ "chpv", "userScriptingPageHcomPage.html#chpv", null ],
        [ "adpv", "userScriptingPageHcomPage.html#adpv", null ],
        [ "adpvl", "userScriptingPageHcomPage.html#adpvl", null ],
        [ "adpvr", "userScriptingPageHcomPage.html#adpvr", null ],
        [ "chds", "userScriptingPageHcomPage.html#chds", null ],
        [ "chdl", "userScriptingPageHcomPage.html#chdl", null ],
        [ "chdlyl", "userScriptingPageHcomPage.html#chdlyl", null ],
        [ "chdlyr", "userScriptingPageHcomPage.html#chdlyr", null ],
        [ "logx", "userScriptingPageHcomPage.html#logx", null ],
        [ "logyl", "userScriptingPageHcomPage.html#logyl", null ],
        [ "logyr", "userScriptingPageHcomPage.html#logyr", null ],
        [ "sapw", "userScriptingPageHcomPage.html#sapw", null ],
        [ "chpw", "userScriptingPageHcomPage.html#chpw", null ],
        [ "dipw", "userScriptingPageHcomPage.html#dipw", null ],
        [ "chpvl", "userScriptingPageHcomPage.html#chpvl", null ],
        [ "chpvr", "userScriptingPageHcomPage.html#chpvr", null ],
        [ "chpvx", "userScriptingPageHcomPage.html#chpvx", null ],
        [ "chto", "userScriptingPageHcomPage.html#chto", null ],
        [ "dito", "userScriptingPageHcomPage.html#dito", null ],
        [ "sapl", "userScriptingPageHcomPage.html#sapl", null ],
        [ "repl", "userScriptingPageHcomPage.html#repl", null ],
        [ "bode", "userScriptingPageHcomPage.html#bode", null ],
        [ "nyquist", "userScriptingPageHcomPage.html#nyquist", null ],
        [ "lock", "userScriptingPageHcomPage.html#lock", null ],
        [ "lockyl", "userScriptingPageHcomPage.html#lockyl", null ],
        [ "lockyr", "userScriptingPageHcomPage.html#lockyr", null ],
        [ "lockx", "userScriptingPageHcomPage.html#lockx", null ]
      ] ],
      [ "Parameter Commands", "userScriptingPageHcomPage.html#parametercommands", [
        [ "dipa", "userScriptingPageHcomPage.html#dipa", null ],
        [ "adpa", "userScriptingPageHcomPage.html#adpa", null ],
        [ "chpa", "userScriptingPageHcomPage.html#chpa", null ],
        [ "sapa", "userScriptingPageHcomPage.html#sapa", null ],
        [ "repa", "userScriptingPageHcomPage.html#repa", null ]
      ] ],
      [ "File Commands", "userScriptingPageHcomPage.html#filecommands", [
        [ "exec", "userScriptingPageHcomPage.html#exec", null ],
        [ "wrhi", "userScriptingPageHcomPage.html#wrhi", null ],
        [ "wrtf", "userScriptingPageHcomPage.html#wrtf", null ],
        [ "pwd", "userScriptingPageHcomPage.html#pwd", null ],
        [ "mwd", "userScriptingPageHcomPage.html#mwd", null ],
        [ "cd", "userScriptingPageHcomPage.html#cd", null ],
        [ "mkdir", "userScriptingPageHcomPage.html#mkdir", null ],
        [ "ls", "userScriptingPageHcomPage.html#ls", null ],
        [ "edit", "userScriptingPageHcomPage.html#edit", null ]
      ] ],
      [ "Variable Commands", "userScriptingPageHcomPage.html#variablecommands", [
        [ "disp", "userScriptingPageHcomPage.html#disp", null ],
        [ "peek", "userScriptingPageHcomPage.html#peek", null ],
        [ "poke", "userScriptingPageHcomPage.html#poke", null ],
        [ "alias", "userScriptingPageHcomPage.html#alias", null ],
        [ "rmvar", "userScriptingPageHcomPage.html#rmvar", null ],
        [ "dihg", "userScriptingPageHcomPage.html#dihg", null ],
        [ "sequ", "userScriptingPageHcomPage.html#sequ", null ],
        [ "ivpv", "userScriptingPageHcomPage.html#ivpv", null ],
        [ "sepl", "userScriptingPageHcomPage.html#sepl", null ],
        [ "dlog", "userScriptingPageHcomPage.html#dlog", null ],
        [ "elog", "userScriptingPageHcomPage.html#elog", null ]
      ] ],
      [ "Model Commands", "userScriptingPageHcomPage.html#modelcommands", [
        [ "load", "userScriptingPageHcomPage.html#load", null ],
        [ "revert", "userScriptingPageHcomPage.html#revert", null ],
        [ "loadr", "userScriptingPageHcomPage.html#loadr", null ],
        [ "save", "userScriptingPageHcomPage.html#save", null ],
        [ "reco", "userScriptingPageHcomPage.html#reco", null ],
        [ "rmco", "userScriptingPageHcomPage.html#rmco", null ],
        [ "chtab", "userScriptingPageHcomPage.html#chtab", null ],
        [ "adco", "userScriptingPageHcomPage.html#adco", null ],
        [ "rpco", "userScriptingPageHcomPage.html#rpco", null ],
        [ "coco", "userScriptingPageHcomPage.html#coco", null ],
        [ "unco", "userScriptingPageHcomPage.html#unco", null ],
        [ "crmo", "userScriptingPageHcomPage.html#crmo", null ]
      ] ],
      [ "Other Commands", "userScriptingPageHcomPage.html#othercommands", [
        [ "help", "userScriptingPageHcomPage.html#help", null ],
        [ "info", "userScriptingPageHcomPage.html#info", null ],
        [ "exit", "userScriptingPageHcomPage.html#exit", null ],
        [ "print", "userScriptingPageHcomPage.html#print", null ],
        [ "eval", "userScriptingPageHcomPage.html#eval", null ],
        [ "set", "userScriptingPageHcomPage.html#set", null ],
        [ "get", "userScriptingPageHcomPage.html#get", null ],
        [ "close", "userScriptingPageHcomPage.html#close", null ],
        [ "fmu", "userScriptingPageHcomPage.html#fmu", null ],
        [ "opt", "userScriptingPageHcomPage.html#opt", null ],
        [ "call", "userScriptingPageHcomPage.html#call", null ],
        [ "echo", "userScriptingPageHcomPage.html#echo", null ],
        [ "semt", "userScriptingPageHcomPage.html#semt", null ],
        [ "sleep", "userScriptingPageHcomPage.html#sleep", null ]
      ] ],
      [ "Local Functions", "userScriptingPageHcomPage.html#functions", [
        [ "abs()", "userScriptingPageHcomPage.html#abs", null ],
        [ "ans()", "userScriptingPageHcomPage.html#ans", null ],
        [ "aver()", "userScriptingPageHcomPage.html#aver", null ],
        [ "bdf1()", "userScriptingPageHcomPage.html#bdf1", null ],
        [ "bdf2()", "userScriptingPageHcomPage.html#bdf2", null ],
        [ "ceil()", "userScriptingPageHcomPage.html#ceil", null ],
        [ "cut()", "userScriptingPageHcomPage.html#cut", null ],
        [ "ddt()", "userScriptingPageHcomPage.html#ddt", null ],
        [ "der()", "userScriptingPageHcomPage.html#der", null ],
        [ "eq()", "userScriptingPageHcomPage.html#eq", null ],
        [ "esd()", "userScriptingPageHcomPage.html#esd", null ],
        [ "euler()", "userScriptingPageHcomPage.html#euler", null ],
        [ "exists()", "userScriptingPageHcomPage.html#exists", null ],
        [ "expand()", "userScriptingPageHcomPage.html#expand", null ],
        [ "expandPowers()", "userScriptingPageHcomPage.html#expandpowers", null ],
        [ "expr()", "userScriptingPageHcomPage.html#expr", null ],
        [ "factor()", "userScriptingPageHcomPage.html#factor", null ],
        [ "fc()", "userScriptingPageHcomPage.html#fc", null ],
        [ "fd()", "userScriptingPageHcomPage.html#fd", null ],
        [ "fft()", "userScriptingPageHcomPage.html#fft", null ],
        [ "floor()", "userScriptingPageHcomPage.html#floor", null ],
        [ "gt()", "userScriptingPageHcomPage.html#gt", null ],
        [ "hg()", "userScriptingPageHcomPage.html#hg", null ],
        [ "imax()", "userScriptingPageHcomPage.html#imax", null ],
        [ "imin()", "userScriptingPageHcomPage.html#imin", null ],
        [ "int()", "userScriptingPageHcomPage.html#int", null ],
        [ "latex()", "userScriptingPageHcomPage.html#latex", null ],
        [ "left()", "userScriptingPageHcomPage.html#left", null ],
        [ "linearize()", "userScriptingPageHcomPage.html#linearize", null ],
        [ "linspace()", "userScriptingPageHcomPage.html#linspace", null ],
        [ "logspace()", "userScriptingPageHcomPage.html#logspace", null ],
        [ "lp1()", "userScriptingPageHcomPage.html#lp1", null ],
        [ "lt()", "userScriptingPageHcomPage.html#lt", null ],
        [ "max()", "userScriptingPageHcomPage.html#max", null ],
        [ "maxof()", "userScriptingPageHcomPage.html#maxof", null ],
        [ "maxpar()", "userScriptingPageHcomPage.html#maxpar", null ],
        [ "min()", "userScriptingPageHcomPage.html#min", null ],
        [ "minof()", "userScriptingPageHcomPage.html#minof", null ],
        [ "minpar()", "userScriptingPageHcomPage.html#minpar", null ],
        [ "obj()", "userScriptingPageHcomPage.html#obj", null ],
        [ "ones()", "userScriptingPageHcomPage.html#ones", null ],
        [ "optpar()", "userScriptingPageHcomPage.html#optpar", null ],
        [ "optvar()", "userScriptingPageHcomPage.html#optvar", null ],
        [ "psd()", "userScriptingPageHcomPage.html#psd", null ],
        [ "rand()", "userScriptingPageHcomPage.html#rand", null ],
        [ "removeDivisors()", "userScriptingPageHcomPage.html#removedivisors", null ],
        [ "right()", "userScriptingPageHcomPage.html#right", null ],
        [ "rms()", "userScriptingPageHcomPage.html#rms", null ],
        [ "rmsd()", "userScriptingPageHcomPage.html#rmsd", null ],
        [ "round()", "userScriptingPageHcomPage.html#round", null ],
        [ "simplify()", "userScriptingPageHcomPage.html#simplify", null ],
        [ "size()", "userScriptingPageHcomPage.html#size", null ],
        [ "ssi()", "userScriptingPageHcomPage.html#ssi", null ],
        [ "td()", "userScriptingPageHcomPage.html#td", null ],
        [ "time()", "userScriptingPageHcomPage.html#time", null ],
        [ "trapezoid()", "userScriptingPageHcomPage.html#trapezoid", null ],
        [ "vector()", "userScriptingPageHcomPage.html#vector", null ],
        [ "x()", "userScriptingPageHcomPage.html#x", null ],
        [ "zeros()", "userScriptingPageHcomPage.html#zeros", null ]
      ] ]
    ] ],
    [ "NumHop Scripting", "userScriptingPageNumHopPage.html", null ]
];